// console.log("Test Alert");
// alert("Hello World");
// document.write("Mamun Khan");
// let a = 10
// let b = 20
// let c = a+b;
//  console.log (c);

 let names1 = ['mamun','monu','benjir','babu','moyna','isma'];
//  names.sort();
//  names.toString();
//  names.pop();
    // names.shift();
//  names.push('parvez');
    // concat
let names2 = ['rakib','masud','rajib'];
let addnames = names1.concat(names2);

 document.write(addnames);
 
//  alert(names[3]);
//  console.log(names[1]);













// document.getElementById('demo').innerHTML = 'names';